# Generated by Django 6.1.1 on 2026-09-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('name_norm', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=2)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'cities',
                'constraints': [models.UniqueConstraint(fields=('name_norm', 'state'), name='uniq_city_state')],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('price', models.FloatField(help_text='USD per gallon')),
            ],
            options={
                'indexes': [models.Index(fields=['lat', 'lng'], name='stations_st_lat_9bcbbb_idx'), models.Index(fields=['price'], name='stations_st_price_92b2c4_idx')],
            },
        ),
    ]
